name: main

on: [push]

env:
  APP_NAME: demo-java

jobs:
  build_deploy_image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start application
        run: make all
      - name: Run tests
        run: make test