name: main

on: [push]

env:
  APP_NAME: demo-java

jobs:
  build_deploy_image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Init application
        run: make init
      - name: Run tests
        run: docker compose -f docker-compose.yaml -f docker-compose-build.yaml up --abort-on-container-exit